= AsciiDoc Live Preview for Adobe Brackets
Thomas Kern
:idprefix:
:idseparator: -


This is an extension for Adobe Brackets http://brackets.io/,
which allows for live preview of AsciiDoc documents.

Most of the work and credits go to Glenn Ruehle for his 
Markdown preview extension (https://github.com/gruehle/MarkdownPreview),
which I ripped off and modified for AsciiDoc.

The actual formatting is performed by
https://github.com/asciidoctor/asciidoctor.js[Asciidoctor.js],
the Javascript incarnation of http://asciidoctor.org/[Asciidoctor].

AsciiDoc mode for CodeMirror was created by 
Thaddee Tyl (https://github.com/espadrine/LivesciiDoc), who
converted the highlighting mode from the Ace editor to CodeMirror.


Other software used:

* http://fortawesome.github.io/Font-Awesome/[Font Awesome 3.2.1] for font icons
* http://highlightjs.org/[highlight.js] for highlighting embedded source code


== Installation

From the Brackets file menu, open the extension manager. Browse available extensions and install 'AsciiDoc Preview'.
This is the recommended way.

As an alternative, you may press the 'Install from URL...' button and
enter https://github.com/nerk/asciidoc-brackets-preview[] into the input field.

After installation, an additional icon appears in the Brackets toolbar to the right. If the name of the file currently edited 
ends with one of the suffixes '.adoc', '.ad', '.asciidoc', or '.asc', pressing this icon displays the preview pane.

In the upper right corner of the preview pane, pressing the gear symbol opens the settings panel.

== Known Issues

* Preamble text directly following the title without an empty line in between is completely suppressed.
* In order to create
a TOC in your document, add attributes
+
----
:toc: 
:toc-placement: preamble
----
to the header of your document. Also make sure that your document
really has a preamble. Other values for +toc+ and +toc-placement+
attributes currently not supported.


== Copyright and License

Copyright (C) 2014 Thomas Kern

Licensed under MIT License. See https://raw.githubusercontent.com/nerk/asciidoc-brackets-preview/master/LICENSE.txt[LICENSE] for details.

Based on 'MarkdownPreview', Copyright (C) 2012 Glenn Ruehle.

AsciiDoc mode Copyright (C) 2014 Thaddee Tyl thaddee.tyl@gmail.com


